"""initial

Revision ID: c7159821742b
Revises: d37fe3559baa
Create Date: 2025-03-25 17:14:31.958166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7159821742b'
down_revision: Union[str, None] = 'd37fe3559baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apitokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('supplies', sa.String(), nullable=True),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apitokens_id'), 'apitokens', ['id'], unique=False)
    op.drop_column('users', 'api_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_apitokens_id'), table_name='apitokens')
    op.drop_table('apitokens')
    # ### end Alembic commands ###
